config/routes.rb
Rails.application.routes.draw do
  get '/artists', to: 'artists#index', as: 'artist'

  get 'artists/:id', to: 'artists#show', as: 'show_artists'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :artist
  has_many :songs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :albums
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :album
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
    @album = @artist.albums
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/index.html.erb
<% @artists.each do |artist| %>
  <div class="col-sm-3">
    <div class="card">
      <img class="card-img-top" src= "<%= artist.image_url%>" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title text-center"><%= artist.name %></h5>
        <%= link_to "Ver info", show_artists_path(artist), class: "btn btn-primary btn-block" %>
      </div>
    </div>
  </div>
<% end %>

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>
<img src="<%= @artist.image_url %>" alt="">
<% @album.each do |album| %>
  <%= album.name %>
  <img src="<%= album.image_url %>" alt="skdks">
  <%= album.released_at %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpotifyV1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Real Music</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to 'Artistas', artist_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#"> Mi música</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#"> Start Yeah</a>
          </li>
        </ul>
        <span class="navbar-text">
          Mi cuenta -
        </span>
      </div>
    </nav>
    <div class="container-fluid">
      <div class="row">
          <%= yield %>
        </div>
      </div>
  </body>
</html>